name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # This is the key change: it tells GitHub to send this job
    # to any available runner that is self-hosted.
    runs-on: self-hosted

    steps:
      # Step 1: Check out the latest code from the main branch
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run the deployment commands directly on the Pi
      - name: Install dependencies and restart bot
        run: |
          # The runner automatically clones the code into a work directory.
          # We need to tell it where our actual project is.
          # Make sure this path is correct!
          cd /home/deployer/moviePicker
          
          # Pull the latest changes (optional but good practice)
          git pull origin main
          
          npm install
          
          # Restart the service using the sudo permission we granted
          sudo pm2 restart moviePicker
